community/urls.py
from django.urls import path
from .views import *

app_name = "community"

urlpatterns = [
    path("", community, name="community"),
    path("<str:id>", detail, name="detail"),
    path("new/", new, name="new"),
    path("create/", create, name="create"),
    path("edit/<str:id>", edit, name="edit"),
    path("update/<str:id>", update, name="update"),
    path("delete/<str:id>", delete, name="delete"),
    path("create_comment/<str:post_id>", create_comment, name="create_comment"),
    path("edit_comment/<str:id>", edit_comment, name="edit_comment"),
    path("update_comment/<str:id>", update_comment, name="update_comment"),
    path("delete_comment/<str:id>", delete_comment, name="delete_comment"),
]

map/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from .views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('grid/',include("grid.urls")),
    path('accounts/',include("allauth.urls")),
    path('users/',include("users.urls")),
    path('community/',include("community.urls")), #Q&A
    path('caution/',include("caution.urls")),
    path('',mainpage,name="mainpage"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

community/models.py
from django.db import models
from django.db.models.deletion import CASCADE
from django.contrib.auth.models import User


class ComPost(models.Model):  # 일반 커뮤니티용 모델
    title = models.CharField(max_length=200)
    writer = models.ForeignKey(User, on_delete=models.CASCADE)
    pub_date = models.DateTimeField()
    body = models.TextField()
    image = models.ImageField(upload_to="community/", null=True, blank=True)


class Comment(models.Model):
    content = models.TextField()
    writer = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(ComPost, on_delete=models.CASCADE, related_name="comments")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

community/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import ComPost, Comment
from django.utils import timezone


def community(request):
    if request.user.is_authenticated:
        posts = ComPost.objects.all()
        return render(request, "community/community.html", {"posts": posts})
    else:
        return redirect("account_login")


def detail(request, id):
    post = get_object_or_404(ComPost, pk=id)
    all_comments = post.comments.all().order_by("-created_at")
    return render(
        request, "community/detail.html", {"post": post, "comments": all_comments}
    )


def new(request):
    return render(request, "community/new.html")


def create(request):
    new_post = ComPost()
    new_post.title = request.POST["title"]
    new_post.writer = request.user
    new_post.pub_date = timezone.now()
    new_post.body = request.POST["body"]
    new_post.image = request.FILES.get("image")
    new_post.save()
    return redirect("community:detail", new_post.id)


def edit(request, id):
    edit_post = ComPost.objects.get(id=id)
    return render(request, "community/edit.html", {"post": edit_post})


def update(request, id):
    update_post = ComPost.objects.get(id=id)
    update_post.title = request.POST["title"]
    update_post.writer = request.user
    update_post.pub_date = timezone.now()
    update_post.body = request.POST["body"]
    if request.FILES.get('image'):
        update_post.image=request.FILES.get('image')
    update_post.save()
    return redirect("community:detail", update_post.id)


def delete(request, id):
    delete_post = ComPost.objects.get(id=id)
    delete_post.delete()
    return redirect("community:community")


def create_comment(request, post_id):
    if request.method == "POST":
        post = get_object_or_404(ComPost, pk=post_id)
        current_user = request.user
        comment_content = request.POST.get("content")
        Comment.objects.create(content=comment_content, writer=current_user, post=post)
    return redirect("community:detail", post_id)


def edit_comment(request, id):
    comment = Comment.objects.get(id=id)
    if request.user == comment.writer:
        return render(request, "community/edit_comment.html", {"comment": comment})
    else:
        return redirect("community:detail", comment.post.id)


def update_comment(request, id):
    comment = Comment.objects.get(id=id)
    comment.content = request.POST.get("content")
    comment.save()
    return redirect("community:detail", comment.post.id)


def delete_comment(request, id):
    comment = Comment.objects.get(id=id)
    if request.user == comment.writer:
        comment.delete()
    return redirect("community:detail", comment.post.id)

community/templates/community/community.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<section style="margin:0px 200px; margin-top:80px; font-family: 'Noto Sans KR', sans-serif;">

<div style="background-size:100%;">

    <h2 style="font-family: 'Nanum Gothic Coding', sans-serif;"> 커뮤니티 </h2>
    <div style="text-align:right;"><a class="btn btn-outline-dark" href="{% url 'community:new'%}">글쓰기</a></div>
    <br>
    <br>

    {%for post in posts%}
    <hr>
    <div style="display:flex; margin: 10px 0px; height: 20vh;">
        <div style="overflow:hidden;margin:0px 30px;width:20vh; height:20vh; border-radius:10%;">

            {%if post.image%}
            <img src="{{ post.image.url }}" style="object-fit: cover; width:100%; height: 100%;" alt="사진">
            {%else%}

            <img src="{% static 'img/meeting.png' %}"
                style=" border-radius:10%; background-color:rgb(255, 255, 255); width:100%; height:100%;" alt="이미지가 어디갔징">

            {%endif%}
        </div>
        <div style="display:flex; flex-direction: column; justify-content: space-around;">
            <h3><a style="text-decoration:none; color:black; font-family: 'Nanum Gothic Coding', sans-serif; " href="{%url 'community:detail' post.id%}">{{post.title}}</a>
            </h3>
   
            <div style=" display:block;">
            작성자 : {{post.writer}}
            <br>
            {{post.pub_date}} 
            </div>
        </div>
    </div>
    {%endfor%}
    <hr>
</div>

</section>
<br>
{% endblock %}

community/templates/community/detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div style= "margin:0px 200px; margin-top:80px; font-family: 'Noto Sans KR', sans-serif;">

<section>
	<h1>{{post.title}}</h1>
    <br>
    <br>
    <div style="text-align:right;">
            작성자 : {{post.writer}} 
            <br>
            {{post.pub_date}}
    </div>
	{%if post.image%}
    	<p>사진 : <img src="{{post.image.url}}" alt="사진"></p> <br><br>
    {%endif%}
    <p style=" height:200px; word-wrap:break-word; overflow:scroll;">
	{{post.body}}
    </p>
	<br><br><br>
	{% if user == post.writer %}
    <a href="{%url 'community:edit' post.id%}" class="btn btn-dark">수정하기</a>
    <a href="{%url 'community:delete' post.id%}" class="btn btn-dark">삭제하기</a>
	{%endif%}
	<hr>
    <h5>Comments</h5>
    {%if user.is_authenticated%}
    <div>
        <form action="{%url 'community:create_comment' post.id%}" method="POST">
            {%csrf_token%}
            <textarea name="content" placeholder="댓글내용입력"></textarea>
            <input type="submit" value="확인">
        </form>
    </div>
    {%endif%}

    <div>
        {%for comment in comments%}
        <div>
            {% if comment.writer %}
                {% if 'user' in comment.writer.username %}
                    작성자 : {{ comment.writer.last_name }} {{ comment.writer.first_name }}
                {% else %}
                    작성자 : {{ comment.writer }}
                {% endif %}
            {% else %}
                작성자 : 알 수 없음
            {% endif %}
            <br>
            댓글 내용:{{comment.content}}<br>
            {%if comment.writer == request.user%}
                <a href="{%url 'community:edit_comment' comment.id %}" class="btn btn-dark">댓글수정</a>
                <a href="{%url 'community:delete_comment' comment.id %}" class="btn btn-dark">댓글삭제</a>
            {%endif%}
        </div><br>
        {%endfor%}
    </div>
</section>
</div>
<br>
{% endblock %}

community/templates/community/edit.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div style="margin:0px 200px; margin-top:80px; font-family: 'Noto Sans KR', sans-serif;">
	<section>
		<form action="{%url 'community:update' post.id%}" method="post" enctype="multipart/form-data">
			{%csrf_token%}
			<p>제목 : <input type="text" name="title" value="{{post.title}}" required></p>
			<p> 사진: <input type="file" name= "image" value="{{post.image}}">{{post.image}}</p>
			<p>내용 :<textarea style="width: 100%;" type="text" name="body" id="" cols="50" rows="10"
				required>{{post.body}}</textarea>
			<button type="submit">제출</button>
		</form>
	</section>

</div>
<br>
{% endblock %}

community/templates/community/edit_comment.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div style= "margin:0px 200px; margin-top:80px; font-family: 'Noto Sans KR', sans-serif;">
	<h4>댓글 내용 수정</h4>
	<form action="{%url 'community:update_comment' comment.id%}" method="POST">
		{%csrf_token%}
		<textarea name="content">{{comment.content}}</textarea>
		<input type="submit" value="확인">
	</form>
</div>

{% endblock %}

community/templates/community/new.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% if user.is_authenticated %}
<div style="margin:0px 200px; margin-top:80px; font-family: 'Noto Sans KR', sans-serif;">

	<section>
		<form action="{%url 'community:create'%}" method="post" enctype="multipart/form-data">
			{%csrf_token%}
			<p>제목 : <input type="text" name="title" required></p>
			<p>사진 : <input type="file" name="image"></p>
			<p>내용 : <textarea style="width: 100%;" type="text" name="body" id="" cols="50" rows="10"
					required></textarea></p>
			<button type="submit">제출</button>
		</form>
	</section>
</div>
{% else %}
<section style="margin:0px 200px; margin-top:80px;">
	<h3>로그인 후 이용가능</h3>
	<br>

	<a href="{% url 'account_login'%}" class="btn btn-dark">로그인</a></li>
	<a href="{% url 'account_signup'%}" class="btn btn-dark">회원가입</a></li>
	<br>
</section>
{%endif%}
<br>
<br>
{% endblock %}