map/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from .views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('grid/',include("grid.urls")),
    path('accounts/',include("allauth.urls")),
    path('users/',include("users.urls")),
    path('community/',include("community.urls")), #Q&A
    path('caution/',include("caution.urls")),
    path('',mainpage,name="mainpage"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import *


app_name="users"
urlpatterns = [
    path("mypage/",mypage,name="mypage"),
    path("myinfo/",myinfo,name="myinfo"),
    path("edit/",edit,name="edit"),
    path("update/",update,name="update"),
    path("introduce/", introduce, name="introduce"),
    path("myQnA/",myQnA,name="myQnA"),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save


# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    ship = models.CharField(null=True,max_length=30) #선박 용도
    ship_name=models.CharField(null=True,max_length=40) #선박명
    tonnage = models.CharField(null=True,max_length=30) # 톤수
    month=models.IntegerField(null=True) #월
    active_sea = models.CharField(null=True,max_length=30) #활동영해
    time_f=models.CharField(null=True, max_length=20) #시간
 

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

users/views.py
from os import write
from community.models import ComPost
from django.shortcuts import get_object_or_404, render, redirect
from .models import *
# Create your views here.

def mypage(request):
    if request.user.is_authenticated:
        user=request.user
        return render(request,"users/mypage.html",{"user":user})
    else:
        return redirect("account_login")


def myinfo(request):
    user=request.user
    return render(request,"users/myinfo.html",{"user":user})


def edit(request):  # 개인만 쓸 페이지
    user = request.user
    return render(request, "users/edit.html", {"user": user})


def update(request):  # 개인만 쓸 함수
    update_profile = request.user.profile
    update_profile.tonnage = request.POST["tonnage"]
    update_profile.ship = request.POST["ship"]
    update_profile.ship_name = request.POST["ship_name"]
    update_profile.month = request.POST["month"]
    update_profile.active_sea = request.POST["active_sea"]
    update_profile.time_f = request.POST["time_f"]
    update_profile.save()

    return redirect("users:myinfo")

def introduce(request):  # 다른 사람들도 접속하면 볼 수 있는 페이지(iframe)
    return render(request, "introduce.html")
   
def myQnA(request):
    myQnA=ComPost.objects.filter(writer=request.user)
    for i in myQnA:
        print(i.id)
    return render(request,"users/myQnA.html",{"myQnA":myQnA})

users/templates/users/edit.html
<div style="background-size:100%; height:600px;">
    <div style="width:50%; height:100%; margin:150px auto; ">
        <form action="{% url 'users:update'%}" method="post" enctype="multipart/form-data" style="text-align:center">
            {%csrf_token%}
            <p>
                <h1>개인정보 등록</h1>
            </p>
            <div style="text-align: left; padding:10vh;">
                <p>
                    <label for="ship">선박 용도 : </label>
                    <select name="ship" id="ship" required>
                        <option value="">선택되지 않음</option>
                        <option value="기타선">기타선</option>
                        <option value="수상레저기구">수상레저기구</option>
                        <option value="어선">어선</option>
                        <option value="여객선">여객선</option>
                        <option value="예인선">예인선</option>
                        <option value="유조선">유조선</option>
                        <option value="화물선">화물선</option>
                    </select>
                </p>
                <p>선박명 : <input type="text" name="ship_name" value="{{user.profile.ship_name}}" required></p>
                <p>
                    <label for="tonnage">톤 수 : </label>
                    <select name="tonnage" id="tonnage" required>
                        <option value="">선택되지 않음</option>
                        <option value="1톤미만">1톤미만</option>
                        <option value="1~2톤미만">1~2톤미만</option>
                        <option value="2~3톤미만">2~3톤미만</option>
                        <option value="3~5톤미만">3~5톤미만</option>
                        <option value="5~10톤미만">5~10톤미만</option>
                        <option value="10~15톤미만">10~15톤미만</option>
                        <option value="15~20톤미만">15~20톤미만</option>
                        <option value="20~25톤미만">20~25톤미만</option>
                        <option value="25~30톤미만">25~30톤미만</option>
                        <option value="30~50톤미만">30~50톤미만</option>
                        <option value="50~100톤미만">50~100톤미만</option>
                        <option value="100~500톤미만">100~500톤미만</option>
                        <option value="100~500톤미만">100~500톤미만</option>
                        <option value="100~500톤미만">100~500톤미만</option>
                        <option value="100~500톤미만">100~500톤미만</option>
                        <option value="500~1,000톤미만">500~1,000톤미만</option>
                        <option value="1000~5000톤미만">1000~5000톤미만</option>
                        <option value="5,000~10,000톤미만">5,000~10,000톤미만</option>
                        <option value="10,000~20,000톤미만">10,000~20,000톤미만</option>
                        <option value="20,000~50,000톤미만">20,000~50,000톤미만</option>
                        <option value="50,000~100,000톤미만">50,000~100,000톤미만</option>
                        <option value="100,000톤이상">100,000톤이상</option>
                        <option value="미상">미상</option>
                    </select>
                </p>
                <p>
                    <label for="month">월 : </label>
                    <select name="month" id="month" required>
                        <option value="">선택되지 않음</option>
                        <option value="1">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="4">4</option>
                        <option value="5">5</option>
                        <option value="6">6</option>
                        <option value="7">7</option>
                        <option value="8">8</option>
                        <option value="9">9</option>
                        <option value="10">10</option>
                        <option value="11">11</option>
                        <option value="12">12</option>
                    </select>
                </p>
                <p>
                    <label for="active_sea">활동 영해 : </label>
                    <select name="active_sea" id="active_sea" required>
                        <option value="">선택되지 않음</option>
                        <option value="개항 및 진입수로">개항 및 진입수로</option>
                        <option value="남해공해">남해공해</option>
                        <option value="남해영해">남해영해</option>
                        <option value="동해공해">동해공해</option>
                        <option value="동해영해">동해영해</option>
                        <option value="서해공해">서해공해</option>
                        <option value="서해영해">서해영해</option>
                        <option value="기타">기타</option>
                    </select>
                </p>
                <p>
                    <label for="time_f">시간 : </label>
                    <select name="time_f" id="time_f" required>
                        <option value="">선택되지 않음</option>
                        <option value="0-4시">0~4시</option>
                        <option value="4-8시">4-8시</option>
                        <option value="8-12시">8-12시</option>
                        <option value="12-16시">12~16시</option>
                        <option value="16-20시">16~20시</option>
                        <option value="20-24시">20시</option>
                    </select>
                </p>
            <button type="submit">제출</button>

            </div>
        </form>
    </div>
</div>

users/templates/users/myQnA.html
{% load static %}
<script language="javascript" type="text/javascript">

    function open_parent_c(t) {

        a = "../../community/" + t
        console.log(a)
        window.parent.location.href = a;
    }

</script>

<div style="background-size:100%; ">

    <h2 style="font-family: 'Nanum Gothic Coding', sans-serif;">내 QnA</h2>

    {%for qna in myQnA%}
    <hr>
    <div style="display:flex; margin: 10px 0px; height: 20vh;">
        <div style="overflow:hidden;margin:0px 30px;width:20vh; height:20vh; border-radius:10%;">
            
            {%if qna.image%}
            <img src="{{ qna.image.url }}" style="object-fit: cover; width:100%; height: 100%;" alt="사진">
            {%else%}
            <img src='{% static "img/meeting.png" %}' style="object-fit: cover; width:100%; height: 100%;" alt="사진">
            {%endif%}
           
        </div>
        <div style="display:flex; flex-direction: column; justify-content: space-around;">

            <h3><a style="text-decoration:none; color:black; font-family: 'Nanum Gothic Coding', sans-serif;" href=""
                    onclick="open_parent_c({{qna.id}})">{{qna.title}}</a>
            </h3>
            작성자 : {{qna.writer}} <br>
            {{qna.pub_date}}

        </div>
    </div>

    {%endfor%}
    <hr>
</div>

users/templates/users/myinfo.html
<div style="background-size:100%; height:600px;">
    <div style="width:50%; height:100%; margin:150px auto; text-align:center;">
      
        <p>
            <h1>개인정보</h1><br>
        </p>
        <div style="text-align: left; padding-left:20vh; padding-right:20vh;">
        <p>선박 용도 :{{user.profile.ship}}</p>
        <p>선박명 :{{user.profile.ship_name}}</p>
        <p>톤 수 :{{user.profile.tonnage}}</p>
        <p>월 :{{user.profile.month}}</p>
        <p>활동 영해 :{{user.profile.active_sea}}</p>
        <p>시간 :{{user.profile.time_f}}</p>

        <input type="button" value="내 정보 수정하기" onclick="location.href='{%url 'users:edit'%}'">
        </div>
    </div>
</div>

users/templates/users/mypage.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<br>
<div style="display:flex;">
    <div style="width:35%; padding:20px;">
        <p>
            <div style="text-align: center; padding: 10px 0;">
                <img style="width: 30%;" src="{% static 'img/ship.png' %}" alt="사진이어디갔징">
            </div>
            <div style="padding: 30px; border: 2px inset black; width:100%; text-align:center; word-break:break-all;">

                <h6>사용자 {{user.profile.user}}</h6> <br>

               
                <input type="button" class="btn btn-default" style="color: brown; width:100%;"
                    onclick="changeIframeUrl('{%url 'users:introduce'%}')" value="사용방법"> <br>
                <input type="button" class="btn btn-default" style="color: brown; width:100%;"
                    onclick="changeIframeUrl('{%url 'users:myinfo'%}')" value="내 정보"> <br>
                <input type="button" class="btn btn-default" style="color: brown; width:100%;"
                    onclick="changeIframeUrl('{%url 'users:myQnA'%}')" value="내 Q&A"> 
               
              

            </div>
        </p>
    </div>
    <div style="width:65%; padding:20px;">
        
        <iframe id="main_frame" name="main_frame" src="{%url 'users:introduce' %}"
            style="width:100%; height:600px; border:none;"></iframe>

    </div>
</div>
<script>
    function changeIframeUrl(url)

    {

        document.getElementById("main_frame").src = url;

    }
</script>


{% endblock %}