caution/urls.py
from django.urls import path
from .views import *


app_name="caution"
urlpatterns = [
    path('',caution,name="caution"),
]

community/urls.py
from django.urls import path
from .views import *

app_name = "community"

urlpatterns = [
    path("", community, name="community"),
    path("<str:id>", detail, name="detail"),
    path("new/", new, name="new"),
    path("create/", create, name="create"),
    path("edit/<str:id>", edit, name="edit"),
    path("update/<str:id>", update, name="update"),
    path("delete/<str:id>", delete, name="delete"),
    path("create_comment/<str:post_id>", create_comment, name="create_comment"),
    path("edit_comment/<str:id>", edit_comment, name="edit_comment"),
    path("update_comment/<str:id>", update_comment, name="update_comment"),
    path("delete_comment/<str:id>", delete_comment, name="delete_comment"),
]

map/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from .views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('grid/',include("grid.urls")),
    path('accounts/',include("allauth.urls")),
    path('users/',include("users.urls")),
    path('community/',include("community.urls")), #Q&A
    path('caution/',include("caution.urls")),
    path('',mainpage,name="mainpage"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import *


app_name="users"
urlpatterns = [
    path("mypage/",mypage,name="mypage"),
    path("myinfo/",myinfo,name="myinfo"),
    path("edit/",edit,name="edit"),
    path("update/",update,name="update"),
    path("introduce/", introduce, name="introduce"),
    path("myQnA/",myQnA,name="myQnA"),
]

map/views.py
from django.shortcuts import redirect, render, get_object_or_404

def mainpage(request):
    return render(request,"mainpage.html")


def test():
     return redirect("mainpage")

map/templates/shared/footer.html
{% load static %}
<footer id="sticky-footer" class="flex-shrink-0 py-4 bg-dark text-white-50" style="bottom: 0%;">
  <div class="container text-center">
    <small>Copyright &copy; BDBA</small>
  </div>
</footer>


<style>
  #sticky-footer {
    bottom: 0;
  }

  #page-content {
    flex: 1 0 auto;
  }
</style>

map/templates/shared/navbar.html
{% load static %}
<!-- Humberger Begin -->
<div class="humberger__menu__overlay"></div>
<div class="humberger__menu__wrapper">
    <div class="humberger__menu__logo">
        <a href="{% url 'mainpage' %}"><img style="width:65px; text-align:center;" src="{% static 'img/logo.png' %}" alt=""></a>
    </div>

    <nav class="humberger__menu__nav mobile-menu">
        <ul>
            <li class="active"><a href="{% url 'mainpage' %}">Home</a></li>
            <li><a href="{% url 'caution:caution'%}">주의사항</a></li>
            <li><a href="{% url 'community:community'%}">Q&A</a></li>
            {%if request.user.is_authenticated%}
            <li><a href="{% url 'users:mypage'%}">Mypage</a></li>
            <li><a href="{% url 'account_logout' %}">Logout</a></li>
            {%else%}
            <li><a href="{% url 'account_login' %}">Login</a></li>
            <li><a href="{% url 'account_signup' %}">Signup</a></li>
            {%endif%}
        </ul>
    </nav>
    <div id="mobile-menu-wrap"></div>
</div>
<!-- Humberger End -->

<!-- Header Section Begin -->
<header class="header">
    <div class="container">
        <div class="row">
            <div class="col-lg-3">
                <div style="text-align:center;" class="header__logo" >
                    <a href="{% url 'mainpage' %}"><img style="width:65px;" src="{% static 'img/logo.png' %}"
                            alt=""></a>
                </div>
            </div>
            <div class="col-lg-6" >
                <nav class="header__menu" style="text-align: center; margin-top:10px; ">
                  
                    <ul>
                        <li><a href="{% url 'mainpage' %}">Home</a></li>
                        <li><a href="{% url 'caution:caution'%}">주의사항</a></li>
                        <li><a href="{% url 'community:community'%}">Q&A</a>
                            <ul class="header__menu__dropdown">
                                <li><a href="{% url 'community:community'%}">Q&A 목록</a></li>
                                {%if request.user.is_authenticated%}
                                <li><a href="{% url 'community:new'%}">글쓰기</a></li>
                                {% endif %}
                            </ul>
                        </li>

                    </ul>
                </nav>
            </div>
            <div class="col-lg-3">
                <div class="header__menu" style="text-align: center;  margin-top:10px;">
                    <ul>
                        <li><a href="">Accounts</a>
                            <ul class="header__menu__dropdown">
                                {%if request.user.is_authenticated%}
                                <li><a href="{% url 'users:mypage' %}">Mypage</a></li>
                                <li><a href="{% url 'account_logout' %}">Logout</a></li>
                                {%else%}
                                <li><a href="{% url 'account_login' %}">Login</a></li>
                                <li><a href="{% url 'account_signup' %}">Signup</a></li>
                                {%endif%}
                            </ul>
                        </li>
                    </ul>

                </div>
            </div>
        </div>
        <div class="humberger__open" style=" margin-top:20px;">
            <i class="fa fa-bars"></i>
        </div>
    </div>
</header>